// ============================================================
// Word Fixer (v30) — normalisasi kata terpecah hasil OCR
// ============================================================
// PaddleOCR sering memecah satu kata menjadi dua token bertetangga
// dengan spasi di tengah: "Dala m", "kerjasa ma", "Ta mbahan".
// Modul ini menggabungkannya kembali secara deterministik:
//
//   1. Kamus kosakata hukum Indonesia (ID_WORD_DICT) — kata utuh
//      yang sah; pasangan token yang gabungannya ada di kamus
//      di-merge.
//   2. Stopword (ID_STOP_WORDS) — kata fungsi yang TIDAK pernah
//      ikut di-merge ("di mana" tidak boleh jadi "dimana").
//   3. Validasi dokumen opsional (docTokens): pasangan di-merge
//      bila bentuk gabungannya muncul sebagai token di dokumen
//      yang sama (penanda kuat bahwa gabungan itu satu kata).
//
// Kebijakan konservatif:
//   - Kedua fragmen harus huruf murni (tanpa angka/punctuation).
//   - Gabungan minimal 6 huruf.
//   - Tidak di-merge bila KEDUA fragmen adalah kata kamus utuh
//     ("kerja sama", "peraturan daerah" = frasa sah, bukan kata
//     terpecah) — kecuali bentuk gabungan muncul di dokumen.
// ============================================================

const ID_WORD_DICT = new Set([
  // ===== Verba legal umum =====
  'menetapkan',
  'ditetapkan',
  'ditetapkanlah',
  'menimbang',
  'mengingat',
  'memutuskan',
  'memperhatikan',
  'menunjuk',
  'membaca',
  'mengatur',
  'diatur',
  'dimaksud',
  'dimaksudkan',
  'dinyatakan',
  'dilaksanakan',
  'dijalankan',
  'diberikan',
  'dipergunakan',
  'diperhatikan',
  'diselenggarakan',
  'dibentuk',
  'dihapuskan',
  'diubah',
  'diganti',
  'diadakan',
  'dilakukan',
  'dibuat',
  'diputuskan',
  'dipertimbangkan',
  'dipungut',
  'dibayarkan',
  'dicabut',
  'diundangkan',
  'diundangkanlah',
  'mengundangkan',
  'memberlakukan',
  'berlaku',
  'menjalankan',
  'menggunakan',
  'memperoleh',
  'melakukan',
  'melaksanakan',
  'menyelenggarakan',
  'membentuk',
  'menghapus',
  'mengubah',
  'mengganti',
  'menambah',
  'mengurangi',
  'meningkatkan',
  'mengawasi',
  'membina',
  'mengembangkan',
  'menyediakan',
  'menganggarkan',
  'membayar',
  'menerima',
  'mengeluarkan',
  'mengelola',
  'menyimpan',
  'menempatkan',
  'mengangkat',
  'memberhentikan',
  'memberikan',
  'menyerahkan',
  'mengumumkan',
  'menyampaikan',
  'meminta',
  'berdasarkan',
  'berkenaan',
  'berhubungan',
  'bertanggungjawab',
  'disebut',
  'disebutkan',
  'ditujukan',
  'dimiliki',
  'dipegang',
  'disimpan',
  'disusun',
  'disahkan',
  'disetujui',
  'dibahas',
  'diproses',
  'dikembalikan',
  'dikurangi',
  'ditambah',
  'ditentukan',
  'ditegaskan',
  'dipertegas',
  'diperkuat',
  'disesuaikan',
  'dikoreksi',
  'diperbaiki',
  'dipelihara',
  'dirawat',
  'dijaga',
  'diamankan',
  'dilindungi',
  'dijamin',
  'merupakan',
  'termasuk',
  'terdiri',
  'terkait',
  'tercantum',
  'tersebut',
  'tersebutlah',
  'menjadi',
  'meningkatkan',
  'mengarahkan',
  'mengkoordinasikan',
  'mengintegrasikan',
  'mensosialisasikan',
  'mengefektifkan',
  'mengefisiensikan',

  // ===== Nomina pemerintahan =====
  'pemerintah',
  'pemerintahan',
  'pemerintahannya',
  'kabupaten',
  'kabupatennya',
  'provinsi',
  'kecamatan',
  'kelurahan',
  'desa',
  'pejabat',
  'warga',
  'masyarakat',
  'masyarakatnya',
  'kesejahteraan',
  'kepentingan',
  'keuangan',
  'keuangannya',
  'anggaran',
  'pendapatan',
  'belanja',
  'pengeluaran',
  'penerimaan',
  'kekayaan',
  'kewajiban',
  'kewenangan',
  'kedudukan',
  'kepala',
  'wakil',
  'sekretaris',
  'bendahara',
  'anggota',
  'pengurus',
  'lembaga',
  'instansi',
  'organisasi',
  'perkumpulan',
  'perusahaan',
  'koperasi',
  'aparatur',
  'pegawai',
  'karyawan',
  'tunjangan',
  'pensiun',
  'kepegawaian',

  // ===== Nomina fiskal & daerah (v30.1) =====
  'pajak',
  'retribusi',
  'daerah',
  'bupati',
  'hukum',
  'alokasi',
  'pengalokasian',
  'penyaluran',
  'mengalokasikan',

  // ===== Nomina hukum & dokumen =====
  'peraturan',
  'peraturannya',
  'keputusan',
  'penetapan',
  'ketentuan',
  'ketentuannya',
  'perundangundangan',
  'perundangan',
  'undangundang',
  'lembaran',
  'berita',
  'penjelasan',
  'penjelasannya',
  'tambahan',
  'lampiran',
  'lampirannya',
  'pengadilan',
  'peradilan',
  'kejaksaan',
  'kepolisian',
  'kehakiman',
  'perjanjian',
  'persetujuan',
  'pertimbangan',
  'permohonan',
  'keberatan',
  'sanggahan',
  'usulan',
  'masukan',
  'rekomendasi',
  'kesepahaman',
  'memorandum',
  'instruksi',
  'edaran',
  'pelanggaran',
  'sanksi',
  'pencegahan',
  'pemberantasan',
  'penertiban',
  'penyidikan',
  'penyelidikan',
  'penuntutan',
  'pemeriksaan',
  'persidangan',
  'administrasi',

  // ===== Nomina program & kegiatan =====
  'pembangunan',
  'pembangunannya',
  'pelaksanaan',
  'pelaksanaannya',
  'perencanaan',
  'pengelolaan',
  'pengawasan',
  'pengembangan',
  'pembinaan',
  'pelayanan',
  'pemeliharaan',
  'penanggulangan',
  'pemberdayaan',
  'peningkatan',
  'perbaikan',
  'perubahan',
  'pertambahan',
  'pengurangan',
  'penggantian',
  'penghapusan',
  'penambahan',
  'kebijakan',
  'kegiatan',
  'pekerjaan',
  'kerja',
  'sama',
  'kerjasama',
  'musyawarah',
  'perwakilan',
  'pemilihan',
  'pengadaan',
  'pemberian',
  'penerimaan',
  'penyusunan',
  'pembentukan',
  'penyelenggaraan',
  'pertanggungjawaban',
  'penyelenggaraannya',
  'perbendaharaan',
  'pelaksanaannya',
  'penghasilan',
  'perekonomian',
  'perindustrian',
  'perdagangan',
  'pariwisata',
  'kebudayaan',
  'pendidikan',
  'kesehatan',
  'ketenagakerjaan',
  'ketenagalistrikan',
  'perhubungan',
  'komunikasi',
  'informatika',
  'telekomunikasi',
  'penyiaran',
  'pertanian',
  'perkebunan',
  'perikanan',
  'peternakan',
  'kehutanan',
  'kelautan',
  'pertambangan',
  'infrastruktur',
  'transportasi',
  'pengangkutan',
  'penyimpanan',
  'pergudangan',
  'distribusi',
  'produksi',
  'konsumsi',
  'pengolahan',
  'pengusahaan',
  'perizinan',
  'pemberdayaan',
  'pemberantasan',
  'penanggulangan',
  'pengelolaannya',
  'pengembangannya',

  // ===== Nomina sektor & sarana =====
  'sampah',
  'rumahtangga',
  'pemilahan',
  'pengomposan',
  'pembakaran',
  'penimbunan',
  'persampahan',
  'kebersihan',
  'keindahan',
  'lingkungan',
  'sumberdaya',
  'sarpras',
  'sarana',
  'prasarana',
  'transportasi',
  'penerangan',
  'jaringan',
  'jembatan',
  'saluran',
  'irigasi',
  'drainase',
  'bangunan',
  'perkantoran',
  'perumahan',
  'pemukiman',
  'permukiman',
  'perpustakaan',
  'laboratorium',
  'puskesmas',
  'posyandu',
  'posyandu',
  'kewirausahaan',
  'agribisnis',
  'peternakan',
  'penyuluhan',
  'permodalan',
  'perkreditan',
  'perbankan',
  'asuransi',
  'perguruan',
  'pesantren',
  'madrasah',
  'sekolah',
  'universitas',
  'kampus',

  // ===== Kata dasar & istilah lain =====
  'dalam',
  'dalamnya',
  'antara',
  'menurutnya',
  'sebagaimana',
  'sedangkan',
  'sedangkan',
  'tentang',
  'terhadap',
  'kepada',
  'padahal',
  'perihal',
  'sehubungan',
  'berkaitan',
  'berkenaan',
  'sepanjang',
  'sejauh',
  'selama',
  'sebelum',
  'sesudah',
  'setelah',
  'sampai',
  'hingga',
  'daripada',
  'kepadanya',
  'kepadanya',
  'daripadanya',
  'terhadapnya',
  'tanggungjawab',
  'tanggungjawabnya',
  'wewenang',
  'urusan',
  'fungsi',
  'tugas',
  'hak',
  'kewajiban',
  'peran',
  'pokok',
  'umum',
  'khusus',
  'penjelasan',
  'pernyataan',
  'penegasan',
  'penutup',
  'penutupnya',
  'awal',
  'akhir',
  'seterusnya',
  'setempat',
  'sekitarnya',
  'seterusnya',
]);

const ID_STOP_WORDS = new Set([
  'di',
  'ke',
  'dan',
  'yang',
  'untuk',
  'dengan',
  'dari',
  'pada',
  'juga',
  'maka',
  'atau',
  'agar',
  'jika',
  'bila',
  'ketika',
  'karena',
  'bahwa',
  'secara',
  'seperti',
  'antara',
  'semua',
  'setiap',
  'masih',
  'sudah',
  'telah',
  'saat',
  'akan',
  'bukan',
  'tidak',
  'ada',
  'adalah',
  'itu',
  'ini',
  'apa',
  'siapa',
  'mana',
  'sini',
  'situ',
  'sana',
  'para',
  'sebesar',
  'sebanyak',
  'kurang',
  'lebih',
  'menurut',
  'sesuai',
  'tentang',
  'sebagaimana',
  'menjadi',
  'melalui',
  'hingga',
  'sampai',
  'seluruh',
  'sebagian',
  'lain',
  'lainnya',
  'tersebut',
  'itu',
  'saja',
  'pula',
  'paling',
  'hanya',
  'juga',
  'harus',
  'wajib',
  'boleh',
  'dapat',
  'dapatlah',
]);

const LETTERS_ONLY_RE = /^[A-Za-z]+$/;

// Coba gabungkan dua token bertetangga menjadi satu kata sah.
// Return string gabungan bila layak, null bila tidak.
function tryMergeWord(a, b, docTokens) {
  if (!a || !b) return null;
  if (a.length < 2) return null;
  if (!LETTERS_ONLY_RE.test(a) || !LETTERS_ONLY_RE.test(b)) return null;

  const la = a.toLowerCase();
  const lb = b.toLowerCase();
  if (ID_STOP_WORDS.has(la) || ID_STOP_WORDS.has(lb)) return null;

  const combined = la + lb;
  if (combined.length < 5) return null;

  const inDict = ID_WORD_DICT.has(combined);
  const inDoc = !!(docTokens && docTokens.has(combined));

  if (!inDict && !inDoc) return null;

  // Kedua fragmen kata utuh = frasa sah ("kerja sama", "peraturan
  // daerah") — jangan digabung, KECUALI bentuk gabungannya memang
  // muncul sebagai token di dokumen yang sama (bukti kuat bahwa
  // gabungan itu satu kata, bukan frasa).
  if (ID_WORD_DICT.has(la) && ID_WORD_DICT.has(lb)) {
    if (!inDoc || !(docTokens && docTokens.has(combined))) return null;
  }

  return a + b;
}

// Gabungkan kata terpecah dalam satu baris teks. docTokens (Set of
// lowercase tokens dari seluruh dokumen) opsional — memperkuat validasi.
function mergeSplitWords(text, docTokens) {
  if (!text) return text;
  const words = text.split(/\s+/);
  if (words.length < 2) return text;

  const out = [];
  for (let i = 0; i < words.length; i++) {
    if (i < words.length - 1) {
      const combined = tryMergeWord(words[i], words[i + 1], docTokens);
      if (combined) {
        out.push(combined);
        i++;
        continue;
      }
    }
    out.push(words[i]);
  }
  return out.join(' ');
}

// Hitung jumlah pasangan kata terpecah (untuk gate retry router):
// berapa pasangan bertetangga yang GABUNGANNYA ada di kamus.
function countSplitWords(text) {
  if (!text) return 0;
  const words = text.split(/\s+/);
  let count = 0;
  for (let i = 0; i < words.length - 1; i++) {
    if (tryMergeWord(words[i], words[i + 1])) count++;
  }
  return count;
}

module.exports = {
  ID_WORD_DICT,
  ID_STOP_WORDS,
  tryMergeWord,
  mergeSplitWords,
  countSplitWords,
};
